version: "3.9"
services:
  web:
    build: .
    command: python eMenu/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "25:25"
    depends_on:
      - db
      - rabbit

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
